headless: true
portal:
  baseUrl: https://alexchumakin.teamcity.com
  host: alexchumakin.teamcity.com
  username: alexchumakin
  password: MFJvZnQ2OEFoWEpCdDg0ZXdydm8=
  repoUrl: https://gitlab.com/alexandrchumakin-docker/node-docker-sample
local:
  baseUrl: http://teamcity:8111
  username: admin
  password: YWRtaW4=
api:
  build:
    id: TestBuild_Build
    projectId: TestBuild
