name: Tests pipeline

on: [push]

jobs:
  tests:
    name: Run test
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Run compose configuration
        run: docker-compose up --abort-on-container-exit
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'target/surefire-reports/*.xml'
